server :
  port: 8080

spring :

  jpa :
    defer-datasource-initialization: true
    hibernate.ddl-auto: create

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://resume-mysql:3306/resume?serverTimezone=UTC&characterEncoding=UTF-8
    username: resumeuser
    password: 232323

  messages:
    basename: errors